In [4]:
import numpy as np

In [17]:
# BRUTE FORCE O(N2) TIME COMPLEXITY
def isUnique(string):
    if len(string)==0 or len(string)==1:
        return ('Is Unique')
    l=0
    r=1
    for l in range(len(string)-1):
        letter=string[l]
        r=l+1
        while r<len(string):
            if string[l]==string[r]:
                return ('Not unique')
            r+=1
    return ('Is Unique')
        

In [22]:
# Using Set (Onlogn) Solution
def isUnique(string):
    str1=set(string)
    if len(str1) == len(string):
        return "Unique"
    else:
        return "Not-Unique" 

In [25]:
name='ara'
isUnique(name)

'Not-Unique'

In [55]:
def checkPermutation(string1, string2):
    s1=sorted(string1)
    s2=sorted(string2)
    if s1==s2:
        return 'Permutation'
    else:
        return 'Not Perumtation'
    
    
    

In [59]:
string1='ry'
string2='yr'
checkPermutation(string1, string2)

'Permutation'

1.3 URLify: Write a method to replace all spaces in a string with'%20'You may assume that the string
has sufficient space at the end to hold the additional characters, and that you are given the "true"
length of the string, (Note: if implementing in Java, please use a character array so that you can
perform this operation in place.)
EXAMPLE
Input: "Mr John Smith
 J, j 13
Output: "Mr%20John%20SmithJ

In [92]:
string="Mr John Smith"
l=len(string)-1
count_sp=0
for i in range(len(string)):
    if string[i]==' ':
        count_sp +=1

new_len =(len(string)-2 )+ 3*2
string=string.ljust(new_len,'*')
string =list(string)

r=new_len -1


while l>=0:
    if string[l]!=' ':
        string[r]=string[l]
        l-=1
        r-=1
    else:
        string[r]='0'
        string[r-1]='2'
        string[r-2]='#'
        r=r-3
        l=l-1

string=''.join(string)

string

'Mr#20John#20Smith'

In [99]:
def palindromePermutation(string):
    count=0
    p_map={}
    string=string.lower().replace(' ','')
    for i in range(len(string)):
        key=string[i]
        if key in p_map.keys():
            p_map[key] = p_map[key]+1
        else:
            p_map[key]=1
    print(p_map)
    
    odd_count=0
    
    for value in p_map.items():
        if value[1] % 2 == 1:
            odd_count+=1
        if odd_count >1:
            return ('Not Valid Permutation')
    return('Valid Permutation')  

    
string='Tac t Coa'  
palindromePermutation(string)

{'t': 2, 'a': 3, 'c': 2, 'o': 1}


'Not Valid Permutation'

In [112]:
def sameLen(s1, s2):
    count=0
    for i in range(len(s1)):
        if s1[i]!= s2[i]:
            count+=1
        if count>1:
            return False
    return True
    
def diffLen(s1,s2):
    count=0
    i=0
    
    while i<(len(s2)):
        if s1[count+i]==s2[i]:
            i+=1
        else:
            count+=1
        if count>1:
            return False
    return True

def oneEditAway(s1, s2):
    s1=s1.lower()
    s2=s2.lower()
    
    len1=len(s1)
    len2=len(s2)
    
    if abs(len1-len2)>1:
        return False
    
    if len1 == len2:
        return sameLen(s1,s2)
    elif len1 > len2:
        return diffLen(s1, s2)
    else:
        return diffLen(s2,s1)
    
  
s1='pale'
s2='paless'
oneEditAway(s1, s2)

False

1,6 String Compression: Implement a method to perform basic string compression using the counts of repeated characters. For example, the string aabcccccaaa would become a2blc5a3. If the"compressed "string would not become smaller than the original string, your method should returnthe original string. You can assume the string has only uppercase and lowercase letters (a - z),

In [175]:
def compressed(string):
    result=[]
    count=1
    for i in range(len(string)):
        if i+1< len(string) and string[i]==string[i+1]:
            count=count+1
        elif count>=1 or i+1>len(string):
            result.append(string[i])
            result.append(str(count))
            count=1
    result=''.join(result)
    return result

    

string= 'aabcccccaaa'
compressed(string)

'a2b1c5a3'

In [18]:
img=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
img

left=0
right=(len(img))-1

while left<right:
    top=left
    bottom=right
    for i in range(right-left):
        temp=img[top][left+i]
        img[top][left+i] = img[bottom-i][left]
        img[bottom-i][left] = img[bottom][right-i]
        img[bottom][right-i]=img[top+i][right]
        img[top+i][right] =temp
        (print(left,right,top,bottom))
    left+=1
    right-=1


0 3 1 3
0 3 1 3
0 3 1 3
1 2 2 2


In [16]:
img

array([[13,  9,  5,  1],
       [14, 10,  6,  2],
       [15, 11,  7,  3],
       [16, 12,  8,  4]])

In [25]:
img=np.array([[1,0,3,4],[5,6,7,8],[0,10,11,12],[13,14,15,16]])
img

array([[ 1,  0,  3,  4],
       [ 5,  6,  7,  8],
       [ 0, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
img=np.array([[1,0,3,4],[5,6,7,8],[5,10,11,12],[13,14,15,16]])

rows= len(img)
cols=len(img[0])

for row in range(rows):
    for col in range(cols):
        if img[row][col]==0:
            img[row,:]='9'
            img[:,col]='9'

for row in range(rows):
    for col in range(cols):
        if img[row][col]==9:
             img[row][col]= 0
img

array([[ 0,  0,  0,  0],
       [ 5,  0,  7,  8],
       [ 5,  0, 11, 12],
       [13,  0, 15, 16]])

In [46]:
def isRotation(str1, str2):
    if len(str1) != len(str2):
        return 'Not a rotation'
    total=str1+str1
    if str2 in total:
        return 'Is a rotation'
    else:
        return 'Not a rotation'

    
str1= 'rehmana'
str2='hmanare'
isRotation(str1, str2)




'Is a rotation'